### ISSUE TITLE
Question about calData.py

### ISSUE THREAD

**Issue by pokaxpoka** [ShiyuLiang/odin-pytorch#1]
At line 63 ~65 of calData.py, you normalize the gradient to the same space of image as follows:

        gradient[0][0] = (gradient[0][0] )/(63.0/255.0)
        gradient[0][1] = (gradient[0][1] )/(62.1/255.0)
        gradient[0][2] = (gradient[0][2])/(66.7/255.0)

I want to know the reason why you introduce above normalization and how to choose the values, i.e., 63.0, 62.1 and 66.7. 

Thanks in advance,
Kimin Lee.

**Comment by igormq** [comment]
I think that those values are the same as the cifar10 normalization.

**Comment by pokaxpoka** [comment]
Thanks! I think that problem is resolved.
